Optimize sourcemap processing
ocsigen/js_of_ocaml pull request #1617
Opened 2024-05-23 13:01 UTC by OlivierNicole

This improves the efficiency of sourcemap processing, chiefly during linking, but also in serializing and deserializing sourcemaps.

Currently, when linking with source maps enabled, js_of_ocaml will decode the source maps for each input file completely into an in-memory explicit mapping, then merge them, then re-encode the merged sourcemap. The merging algorithm involves superlinear sorting operations. However, the format of sourcemaps allows to avoid sorting for the concatenation of generated files.

In addition, all operations performed by linking (concatenation of files, removal and addition of lines) can be performed directly on the encoded form, which further avoids a full parsing to an in-memory representation.

When compiling js_of_ocaml with itself, the final linking step is accelerated by a speedup of about 2.3x with OCaml 5.2.0+fp:

| recent trunk | this PR |
|--------------------|------------|
| 331.8 ms ±   6.1 ms | 143.3 ms ±   1.1 ms |

2024-05-23 14:21 UTC, OlivierNicole commented
I can’t seem to reproduce the CI failure:

```
File "toplevel/examples/lwt_toplevel/dune", line 2, characters 8-16:
2 |  (names toplevel)
            ^^^^^^^^
(cd _build/default/toplevel/examples/lwt_toplevel && ../../../compiler/bin-js_of_ocaml/js_of_ocaml.exe link --source-map-inline -o toplevel.bc.js .toplevel.eobjs/jsoo/toplevel.bc.runtime.js ../../../.js/!effects+toplevel/stdlib/stdlib.cma.js ../../../.js/!effects+toplevel/compiler-libs.common/ocamlcommon.cma.js ../../../.js/!effects+toplevel/compiler-libs.bytecomp/ocamlbytecomp.cma.js ../../../.js/!effects+toplevel/menhirLib/menhirLib.cma.js ../../../.js/!effects+toplevel/gen/gen.cma.js ../../../.js/!effects+toplevel/sedlex/sedlex.cma.js ../../../.js/!effects+toplevel/yojson/yojson.cma.js ../../../compiler/lib/.js_of_ocaml_compiler.objs/jsoo/!effects+toplevel/js_of_ocaml_compiler.cma.js ../../../lib/runtime/.jsoo_runtime.objs/jsoo/!effects+toplevel/jsoo_runtime.cma.js ../../../lib/js_of_ocaml/.js_of_ocaml.objs/jsoo/!effects+toplevel/js_of_ocaml.cma.js ../../../.js/!effects+toplevel/uutf/uutf.cma.js ../../../.js/!effects+toplevel/re/re.cma.js ../../../.js/!effects+toplevel/tyxml.functor/tyxml_f.cma.js ../../../.js/!effects+toplevel/tyxml/tyxml.cma.js ../../../.js/!effects+toplevel/react/react.cma.js ../../../.js/!effects+toplevel/reactiveData/reactiveData.cma.js ../../../lib/tyxml/.js_of_ocaml_tyxml.objs/jsoo/!effects+toplevel/js_of_ocaml_tyxml.cma.js ../../../compiler/lib-dynlink/.js_of_ocaml_compiler_dynlink.objs/jsoo/!effects+toplevel/js_of_ocaml_compiler_dynlink.cma.js ../../../.js/!effects+toplevel/compiler-libs.toplevel/ocamltoplevel.cma.js ../../lib/.js_of_ocaml_toplevel.objs/jsoo/!effects+toplevel/js_of_ocaml_toplevel.cma.js ../../../.js/!effects+toplevel/lwt/lwt.cma.js ../../../lib/lwt/.js_of_ocaml_lwt.objs/jsoo/!effects+toplevel/js_of_ocaml_lwt.cma.js ../../../.js/!effects+toplevel/graphics/graphics.cma.js ../../../lib/deriving_json/.js_of_ocaml_deriving.objs/jsoo/!effects+toplevel/js_of_ocaml_deriving.cma.js ../../../.js/!effects+toplevel/str/str.cma.js ../../../.js/!effects+toplevel/dynlink/dynlink.cma.js ../../../lib/lwt/graphics/.graphics_js.objs/jsoo/!effects+toplevel/graphics_js.cma.js ../../../.js/!effects+toplevel/ocaml-compiler-libs.common/ocaml_common.cma.js ../../../.js/!effects+toplevel/ppxlib.astlib/astlib.cma.js ../../../.js/!effects+toplevel/stdlib-shims/stdlib_shims.cma.js ../../../.js/!effects+toplevel/ppxlib.ast/ppxlib_ast.cma.js ../../../.js/!effects+toplevel/ocaml-compiler-libs.shadow/ocaml_shadow.cma.js ../../../.js/!effects+toplevel/ppxlib.print_diff/ppxlib_print_diff.cma.js ../../../.js/!effects+toplevel/ppx_derivers/ppx_derivers.cma.js ../../../.js/!effects+toplevel/ppxlib.traverse_builtins/ppxlib_traverse_builtins.cma.js ../../../.js/!effects+toplevel/sexplib0/sexplib0.cma.js ../../../.js/!effects+toplevel/ppxlib.stdppx/stdppx.cma.js ../../../.js/!effects+toplevel/ppxlib/ppxlib.cma.js ../../../ppx/ppx_js/as-lib/.ppx_js.objs/jsoo/!effects+toplevel/ppx_js.cma.js ../../../ppx/ppx_js/lib/.ppx_js_rewriter.objs/jsoo/!effects+toplevel/ppx_js_rewriter.cma.js .toplevel.eobjs/jsoo/dune__exe.cmo.js .toplevel.eobjs/jsoo/dune__exe__B64.cmo.js .toplevel.eobjs/jsoo/dune__exe__Colorize.cmo.js .toplevel.eobjs/jsoo/dune__exe__Graphics_support.cmo.js .toplevel.eobjs/jsoo/dune__exe__Ocp_indent.cmo.js .toplevel.eobjs/jsoo/dune__exe__Indent.cmo.js .toplevel.eobjs/jsoo/dune__exe__Ppx_support.cmo.js .toplevel.eobjs/jsoo/dune__exe__Toplevel.cmo.js ../../../.js/!effects+toplevel/stdlib/std_exit.cmo.js --linkall)
../../../compiler/bin-js_of_ocaml/js_of_ocaml.exe: You found a bug. Please report it at https://github.com/ocsigen/js_of_ocaml/issues :
Error: File "compiler/lib/source_map_io.yojson.ml", line 109, characters 12-18: Assertion failed
```

This test builds fine on my machine.

2024-05-23 15:09 UTC, OlivierNicole commented
One test is failing because reading “index maps” (composite source maps) is not supported for now—something that is not required for js_of_ocaml to function. I will fix this test soon.

2024-05-24 15:56 UTC, rickyvetter commented
I just tested this change on an incremental build for one of our largest executables and am getting this timing for `js_of_ocaml link`.

Pre: 2.469s
Post: 1.301s

Very cool!

2024-06-04 14:06 UTC, OlivierNicole commented
This is ready for review. I don’t quite understand the build problems on the 5.1 CI, but they don’t seem related to this PR.

2024-06-17 07:58 UTC, hhugo commented on compiler/lib/source_map.ml
> +  external of_string : string -> t = "%identity"
This is dangerous, it should just be `let of_string x = Uninterpreted x`

2024-06-17 07:59 UTC, hhugo commented on compiler/lib/source_map.ml
> +  external to_string : t -> string = "%identity"
```suggestion
  let to_string (Uninterpreted x) = x
```

2024-06-17 08:00 UTC, hhugo commented on compiler/lib/source_map.ml
> +  external of_json_string : string -> t = "%identity"
```suggestion
  let of_json_string x = Uninterpreted x
```

2024-06-17 08:00 UTC, hhugo commented on compiler/lib/source_map.ml
> +  external to_json_string : t -> string = "%identity"
```suggestion
  let to_json_string (Uninterpreted x) = x
```

2024-06-17 12:30 UTC, hhugo commented on compiler/lib/js_output.ml
> +          let* r = contents in
I would avoid introducing `let*` syntax here to respect the style of codebase.

Just use the following maybe
```ocaml
Option.map (fun x -> List.rev !x) contents
```

2024-06-17 12:33 UTC, hhugo commented on compiler/lib/link_js.ml
> +          let _ = write ?source t s ~add:(fun n -> lcount := !lcount + n + 1) in
```suggestion
          let () = write ?source t s ~add:(fun n -> lcount := !lcount + n + 1) in
```

2024-07-01 12:40 UTC, hhugo commented on compiler/lib/source_map.ml
> +  let sum_offsets_line ~carry_source ~carry_line ~carry_col ~carry_name ~pos ~len str =
and this update_carries_from_line ?

2024-07-16 10:02 UTC, OlivierNicole commented
Is anything blocking this PR still?

2024-07-22 11:17 UTC, hhugo requested changes
I've pushed some minor cleanup on the branch directly.

I think this goes in the right direction.

Changes would be easier to digest if they were in separate commits.

My understanding is that the Line_edits change is what gives use the most part of the improvement. Could we achieve similar perf using sections (Index sourcemap) ?

2024-07-22 11:17 UTC, hhugo commented on compiler/lib/source_map_io.yojson.ml
> +      | `Intlit version when Int.equal (int_of_string version) 3 -> ()
Can't we merge IntLit with FloatLit  ?
```
(`FloatLit version | `IntLit version)  when Float.equal (Float.of_string version) 3.0 -> ..
```

2024-07-22 11:17 UTC, hhugo commented on compiler/lib/source_map_io.yojson.ml
> +            { Index.version = 3; file = Option.value file ~default:""; sections }
We should check and assert the version instead of assuming it's `3`

2024-07-22 11:17 UTC, hhugo commented on compiler/lib/source_map.mli
> +  val to_json_string : t -> string
This could return a
```
[`StringLit of string ]
```
to make its usage explicit

2024-07-22 12:51 UTC, hhugo commented on compiler/lib/source_map.ml
> +    try of_json (Yojson.Basic.from_string s)
see https://github.com/ocsigen/js_of_ocaml/pull/1639

2024-07-22 14:39 UTC, hhugo commented on compiler/lib/source_map_io.yojson.ml
> +      | `Intlit version when Int.equal (int_of_string version) 3 -> ()
Thinking about this more, maybe we shouldn't handle FloatLit at all

2024-07-30 15:13 UTC, OlivierNicole commented
> My understanding is that the Line_edits change is what gives use the most part of the improvement. Could we achieve similar perf using sections (Index sourcemap) ?

I hoped so initially, but it turns out that `Link_js` may remove or add metadata comments in the middle of a compilation unit, which pretty much killed my hope of simply using index maps.

2024-07-31 09:32 UTC, OlivierNicole commented on compiler/tests-compiler/sourcemap.ml
> +    CASU;;GCUU;;;;;;;;;;;;;;;;;;;;GCff;
Yes but it’s more complicated to implement :p But sure I’ll do it

2024-07-31 09:32 UTC, OlivierNicole commented on compiler/lib/source_map.ml
> +    try of_json (Yojson.Basic.from_string s)
Thanks! I rebased on that.

2024-07-31 09:32 UTC, OlivierNicole commented on compiler/lib/source_map.ml
> +module Source_text = struct
> Is the introduction of Source_text really giving improvement ? By how much ?

It was non-negligible, yes. I’ll re-do some measurements.

2024-07-31 09:33 UTC, OlivierNicole commented
Never mind, apparently I had started a review at some point in the past and never completed it, and apparently Github considers all your comments henceforth as pending

2024-07-31 15:19 UTC, hhugo commented on compiler/lib/source_map.ml
> +module Source_text = struct
Can you run the benchmark with master vs  #1640 alone ?

2024-07-31 16:19 UTC, OlivierNicole commented on compiler/lib/source_map.ml
> +module Source_text = struct
master (51cce06448): 3.022 s ±  0.028 s
#1640:  2.851 s ±  0.021 s (1.06 times faster)

2024-08-02 15:48 UTC, OlivierNicole commented
Just to make sure we are on the same page, my intention is to wait for #1640 to be merged, rebase on it, and then address the rest of your new review (thanks!).

2024-08-02 20:56 UTC, hhugo commented
> Just to make sure we are on the same page, my intention is to wait for #1640 to be merged, rebase on it, and then address the rest of your new review (thanks!).

What do you think about the following, on top of #1640.
- drop the indexed sourcemap for now (it seems it's not used)
- first merge the delayed/on demand decoding that replace the sourcemap change from #1654  
- keep this PR for "edit un-decoded mapping" only.

2024-08-02 21:00 UTC, OlivierNicole commented
> drop the indexed sourcemap for now (it seems it's not used)

It is used, to represent the sourcemap of the linker output (in Link_js).

2024-09-04 08:11 UTC, hhugo commented
#1640 has been merged, I'll let you rebase this one

2024-09-04 13:14 UTC, OlivierNicole commented
Done

2024-09-05 09:35 UTC, hhugo commented on compiler/tests-sourcemap/dump_sourcemap.ml
> +let print_mapping lines ?(line_offset = 0) (sm : Source_map.t) =
I would make line_offset non-optional

2024-09-05 10:03 UTC, hhugo commented
I'm not very happy with the callback based approach used on `Link_js`. Without thinking much about it, I would assume that one could reconstruct the edit instruction inside `let copy ic oc = ...` only.

Maybe we could move the handling/parsing of Sourcemap index into a separate PR to remove some noise in here.

2024-09-05 10:12 UTC, hhugo commented
Regarding the representations of edits. We currently have per line instructions. Have you considered using a different approach (closer to what's done on master with `reloc`) using "copy n lines starting at pos n into position m" ?

2024-09-05 12:54 UTC, OlivierNicole commented
I considered it, but at the time discarded it as early optimisation. Now that the main source of slowdown as been eliminated, it might be worth trying.

2024-10-10 15:47 UTC, OlivierNicole commented
> Regarding the representations of edits. We currently have per line instructions. Have you considered using a different approach (closer to what's done on master with `reloc`) using "copy n lines starting at pos n into position m" ?

Actually, what I had considered was to have the edits represented as a list of “copy / delete n lines” rather than a long list of “copy / delete 1 line”.

What you suggest would make `Source_map.Mappings.edit` no longer linear. In your suggestion, some sorting is involved, whereas in what is currently done, the destination line is implicitly represented by the position of the edit in the list of edits.

2024-10-15 14:24 UTC, hhugo commented
> > My understanding is that the Line_edits change is what gives use the most part of the improvement. Could we achieve similar perf using sections (Index sourcemap) ?
> 
> I hoped so initially, but it turns out that `Link_js` may remove or add metadata comments in the middle of a compilation unit, which pretty much killed my hope of simply using index maps.

Can we maybe revisit this approach. Maybe we could  teach link_js to copy blocks of lines that do not mess up with sourcemap ? If we really want to drop comments, we could emit an empty line instead. We would probably need to emit Index map when compiling cma files so that we have one sourcemap per unit and we can easily drop dead units when linking.

2024-10-17 12:37 UTC, hhugo commented
I've opened #1715 instead. It removes the need to change encoded mappings.

2024-10-22 08:02 UTC, closed without merging